apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: uptime-kuma
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: statefulset
    name: uptime-kuma
  targetCPUUtilizationPercentage: 80
